SELECT p.party_id,
	   p.public_party_id,
       p.party_type,
       p.user_id,
       p.party_audit_id,
       p.ip_address,
       p.language_id,
       p.year_established,
       p.version_number,
       p.event_type,
       p.last_modified_by,
       p.event_datetime,
       p.license_link,
       p.company_logo_link,
       p.company_name_english,
       p.company_name_chinese,
       p.company_description,
       p.number_of_employees,
       p.company_website,
       p.total_annual_sales,
       p.total_imports_us_dollars,
       p.first_name,
       p.last_name,
       p.mobile_phone,
       p.business_phone,
       p.skype_id,
       p.msn_id,
       p.icq_id,
       p.email_address,
       p.province,
       p.gender,
       p.title,
       p.country,
       p.registration_date,
       CASE WHEN ul.username IS NULL THEN pu.username ELSE ul.username END as username
FROM latest_party_view p 
LEFT OUTER JOIN user_login AS ul ON ul.user_id = p.user_id
LEFT OUTER JOIN pending_user AS pu ON pu.party_id = p.party_id