SELECT abv.party_id, 
	   abv.public_party_id,
       abv.party_audit_id,
       ip_address,
       abv.event_type,
       abv.version_number,
       abv.business_phone,
       abv.mobile_phone,
       abv.company_name_english,
       abv.company_name_chinese,
       abv.company_description,
       abv.number_of_employees, 
       abv.company_website, 
       abv.year_established, 
       abv.total_annual_sales,
       abv.total_imports_us_dollars,
       abv.first_name, 
       abv.last_name, 
       abv.skype_id, 
       abv.msn_id, 
       abv.icq_id, 
       abv.email_address, 
       abv.gender, 
       abv.country, 
       abv.license_link,
       abv.company_logo_link,
       abv.title,
       abv.province,
       registration_date
FROM approved_buyer_view AS abv
WHERE abv.party_id = :partyId
