SELECT p.party_id,
a.username, a.first_name, a.last_name, 
a.email_address, a.company_name_english, a.role_description,
a.event_type as user_event_type,
       p.membership_level_id,
       p.date_purchased,
       p.level,
       p.base_price,
       p.price_at_purchase,
       p.price_paid,
       p.membership_id,
       p.number_of_messages,
       p.company_showroom,
       p.hot_product_listing,
       p.product_alert,
       p.supplier_to_supplier_inquiry,
       p.export_to_china_tutorial,
       p.enhance_profile,
       p.third_party_verification,
       p.website_and_advanced_email,
       p.effective_date,
       p.video,
       p.contact_china_direct,
       p.market_analysis,
  	   p.buyer_search,
       p.logistics_assistance,
       p.number_of_products,
       p.number_of_translations,
       p.expiration_date,
       p.payment_type,
       p.payment_invoice,
       p.renewal_discount_amount,
       p.upgrade_credit_amount,
       p.membership_audit_id,
       p.event_type as membership_event_type,
       p.version_number
FROM  provisional_membership_view p 
left join user_view a on a.party_id = p.party_id
WHERE p.event_type = 'Provisional'