DROP SCHEMA PUBLIC CASCADE

-- REFERENCE DATA

CREATE TABLE business_type
(
  business_type_id    Bigint       NOT NULL  PRIMARY KEY,
  business_type_name  Varchar(50)  NOT NULL,
  is_active           Boolean      DEFAULT TRUE  NOT NULL,
  last_modified_by    Varchar(75)  NOT NULL,
  last_modified_date  Timestamp    NOT NULL
)
;

CREATE TABLE subscription_type
(
  subscription_type_id         Bigint       NOT NULL  PRIMARY KEY,
  subscription_type_name       Varchar(50)  NOT NULL,
  last_modified_by         Varchar(75)  NOT NULL,
  last_modified_date       Timestamp    NOT NULL
)
;

CREATE TABLE language
(
  language_id         Bigint       NOT NULL  PRIMARY KEY,
  language_name       Varchar(50)  NOT NULL,
  abbreviation        Varchar(2)   NOT NULL,
  last_modified_by    Varchar(75)  NOT NULL,
  last_modified_date  Timestamp    NOT NULL
)
;

CREATE TABLE message_tag
(
  message_tag_id      Bigint       NOT NULL  PRIMARY KEY,
  message_tag_name    Varchar(50)  NOT NULL,
  is_active           Boolean      DEFAULT TRUE  NOT NULL,
  last_modified_by    Varchar(75)  NOT NULL,
  last_modified_date  Timestamp    NOT NULL
)
;

CREATE TABLE application_parameter
(
  application_parameter_id     Bigint       NOT NULL  PRIMARY KEY,
  application_parameter_name   Varchar(50)  NOT NULL,
  application_parameter_value  Varchar(50)  NOT NULL,
  last_modified_by             Varchar(75)  NOT NULL,
  last_modified_date           Timestamp    NOT NULL
)
;

-- USER SUBJECT AREA

CREATE TABLE user_login
(
  user_id                      Bigint        NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  username                     Varchar(75)   NOT NULL,
  password                     Varchar(128)  NOT NULL,
  enabled                      Boolean       DEFAULT TRUE  NOT NULL,
  failures_since_last_success  TinyInt       NOT NULL,
  last_modified_by             Varchar(75)   NOT NULL,
  last_modified_date           Timestamp     NOT NULL
)
;

CREATE TABLE user_role
(
  user_role_id        Bigint       NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  user_id             Bigint       NOT NULL,
  role_description    Varchar(30)  NOT NULL,
  last_modified_by    Varchar(75)  NOT NULL,
  last_modified_date  Timestamp    NOT NULL
)
;

CREATE TABLE persistent_logins
(
  series     Varchar(64)  NOT NULL  PRIMARY KEY,
  username   Varchar(75)  NOT NULL,
  token      Varchar(64)  NOT NULL,
  last_used  Timestamp    NOT NULL
)
;

CREATE TABLE pending_user
(
  pending_user_id      Bigint        NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  confirmation_token   Varchar(50)   NOT NULL,
  username             Varchar(75)   NOT NULL,
  password             Varchar(128)  NOT NULL,
  party_id             Bigint        NOT NULL,
  last_modified_by     Varchar(75)   NOT NULL,
  last_modified_date   Timestamp     NOT NULL
)
;

-- PARTY (BUSINESS/SUPPLIER) SUBJECT AREA

CREATE TABLE party
(
  party_id            Bigint       NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  public_party_id     Varchar(20)  NULL,
  user_id             Bigint       NULL,
  registration_date   Date         NOT NULL,
  ip_address          Varchar(39)  NULL,
  language_id         Bigint       NULL,
  legacy_uid          Bigint       NULL,
  last_modified_by    Varchar(75)  NOT NULL,
  last_modified_date  Timestamp    NOT NULL
)
;
CREATE UNIQUE INDEX public_party_id_AK ON party (public_party_id);

CREATE TABLE party_audit
(
  party_audit_id            Bigint          NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  party_type                Varchar(20)  NOT NULL,
  company_name_english      Varchar(80),
  company_name_chinese      Varchar(50),
  company_description       Varchar(4000),
  number_of_employees       Varchar(50),
  company_website           Varchar(70),
  year_established          Int,
  total_annual_sales        Varchar(50),
  total_imports_us_dollars  Varchar(50),
  first_name                Varchar(50),
  last_name                 Varchar(50),
  mobile_phone              Varchar(20),
  business_phone            Varchar(50),
  skype_id                  Varchar(32),
  msn_id                    Varchar(75),
  icq_id                    Varchar(75),
  email_address             Varchar(75),
  province                  Varchar(50),
  gender                    Varchar(20),
  country                   Varchar(75),
  license_link              Varchar(100),
  company_logo_link         Varchar(100),
  video_link                Varchar(2000),
  title                     Varchar(20),
  last_modified_by          Varchar(75)     NOT NULL,
  last_modified_date        Timestamp       NOT NULL
)
;

CREATE TABLE party_audit_business_type
(
  party_audit_id      Bigint       NOT NULL,
  business_type_id    Bigint       NOT NULL,
  last_modified_by    Varchar(75)  NOT NULL,
  last_modified_date  Timestamp    NOT NULL
)
;

CREATE TABLE party_audit_translation
(
  party_audit_translation_id  Bigint         NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  language_id                 Bigint         NOT NULL,
  party_audit_id              Bigint         NOT NULL,
  company_description         Varchar(4000),
  last_modified_by            Varchar(75)    NOT NULL,
  last_modified_date          Timestamp      NOT NULL
)
;

CREATE TABLE party_audit_status
(
  party_audit_status_id  Bigint       NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  party_id               Bigint       NOT NULL,
  party_audit_id         Bigint       NOT NULL,
  version_number         Int          NOT NULL,
  event_type             Varchar(30)  NOT NULL,
  event_datetime         Timestamp    NOT NULL,
  last_modified_by       Varchar(75)  NOT NULL,
  last_modified_date     Timestamp    NOT NULL
)
;

-- MEMBERSHIP SUBJECT AREA

CREATE TABLE membership_tier
(
  membership_tier_id              Bigint         NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  tier                            TinyInt        NOT NULL,
)
;

CREATE TABLE renewal_credit_schedule
(
  renewal_credit_schedule_id      Bigint         NOT NULL  GENERATED BY DEFAULT AS IDENTITY,  
  membership_tier_id              Bigint         NOT NULL,
  months_remaining                TinyInt        NOT NULL,
  percent_amount                  Decimal(18,3)  DEFAULT 0      NOT NULL, 
)
;

CREATE TABLE membership_level
(
  membership_level_id             Bigint         NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  membership_tier_id              Bigint         NOT NULL,
  term                            TinyInt        NOT NULL,
  base_price                      Decimal(18,3)  NOT NULL,
  number_of_product               Int            NOT NULL,
  number_of_messages              Bigint         NOT NULL,
  number_of_translations          Int            NOT NULL,
  company_showroom                Boolean        DEFAULT TRUE   NOT NULL,
  hot_product_listing             Int            DEFAULT 0      NOT NULL,
  product_alert                   Boolean        DEFAULT FALSE  NOT NULL,
  supplier_to_supplier_inquiry    Boolean        DEFAULT FALSE  NOT NULL,
  export_to_china_tutorial        Boolean        DEFAULT FALSE  NOT NULL,
  enhance_profile                 Int            DEFAULT 0      NOT NULL,
  third_party_verification        Boolean        DEFAULT FALSE  NOT NULL,
  website_and_advanced_email      Boolean        DEFAULT FALSE  NOT NULL,
  video                           Boolean        DEFAULT FALSE  NOT NULL,
  contact_china_direct            Boolean        DEFAULT FALSE  NOT NULL,
  market_analysis                 Boolean        DEFAULT FALSE  NOT NULL,
  buyer_search                    Boolean        DEFAULT FALSE  NOT NULL,
  logistics_assistance            Boolean        DEFAULT FALSE  NOT NULL,
  effective_date                  Date           NOT NULL,
  expiration_date                 Date           NOT NULL,
  last_modified_by                Varchar(75)    NOT NULL,
  last_modified_date              Timestamp      NOT NULL
)
;

CREATE TABLE discounts
(
  discounts_id          Bigint         NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  discount_code         Varchar(45)    NOT NULL,
  discount_amount_type  Varchar(45)    NOT NULL,
  amount                Decimal(18,3)  DEFAULT 0      NOT NULL,  
  description           Varchar(45)    NOT NULL,
  ongoing               Boolean        DEFAULT FALSE   NOT NULL,
  special               Boolean        DEFAULT FALSE   NOT NULL,
  effective_date        Date           NOT NULL,
  expiration_date       Date           NOT NULL,
  last_modified_by      Varchar(75)    NOT NULL,
  last_modified_date    Timestamp      NOT NULL
)
;

CREATE TABLE discounts_membership_tier
(
  discounts_membership_tier_id Bigint           NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  discounts_id                 Bigint           NOT NULL,
  membership_tier_id           Bigint           NOT NULL,
  last_modified_by             Varchar(75)      NOT NULL,
  last_modified_date           Timestamp        NOT NULL
)
;

CREATE TABLE discounts_subscription_type
(  
  discounts_subscription_type_id  Bigint           NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  discounts_id                    Bigint           NOT NULL,
  subscription_type_id            Bigint           NOT NULL,
  last_modified_by                Varchar(75)      NOT NULL,
  last_modified_date              Timestamp        NOT NULL
)
;

CREATE TABLE membership
(
  membership_id                 Bigint         NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  party_id                      Bigint         NOT NULL,
  last_modified_by              Varchar(75)    NOT NULL,
  last_modified_date            Timestamp      NOT NULL
)
;

CREATE TABLE membership_audit
(
  membership_audit_id           Bigint         NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  membership_level_id           Bigint         NOT NULL,
  date_purchased                Date           NOT NULL,
  term                          TinyInt        NOT NULL,
  price_at_purchase             Decimal(18,3)  NOT NULL,
  effective_date                Date           NOT NULL,
  base_price                    Decimal(18,3)  NOT NULL,
  number_of_messages            Bigint         NOT NULL,
  company_showroom              Boolean        DEFAULT TRUE   NOT NULL,
  hot_product_listing           Int            DEFAULT 0      NOT NULL,
  product_alert                 Boolean        DEFAULT FALSE  NOT NULL,
  supplier_to_supplier_inquiry  Boolean        DEFAULT FALSE  NOT NULL,
  export_to_china_tutorial      Boolean        DEFAULT FALSE  NOT NULL,
  enhance_profile               Int            DEFAULT 0      NOT NULL,
  third_party_verification      Boolean        DEFAULT FALSE  NOT NULL,
  website_and_advanced_email    Boolean        DEFAULT FALSE  NOT NULL,
  video                         Boolean        DEFAULT FALSE  NOT NULL,
  contact_china_direct          Boolean        DEFAULT FALSE  NOT NULL,
  market_analysis               Boolean        DEFAULT FALSE  NOT NULL,
  buyer_search                  Boolean        DEFAULT FALSE  NOT NULL,
  logistics_assistance          Boolean        DEFAULT FALSE  NOT NULL,
  number_of_products            Int            NOT NULL,
  number_of_translations        Int            NOT NULL,
  expiration_date               Date           NOT NULL,
  price_paid                    Decimal(18,3),
  payment_type                  Varchar(75)    NOT NULL,
  payment_invoice               Varchar(75),
  renewal_discount_amount       Decimal(18,3)  NOT NULL,
  upgrade_credit_amount         Decimal(18,3)  NOT NULL,
  last_modified_by              Varchar(75)    NOT NULL,
  last_modified_date            Timestamp      NOT NULL
)
;

CREATE TABLE membership_audit_discounts
(
  membership_audit_discounts_id       Bigint         NOT NULL  GENERATED BY DEFAULT AS IDENTITY,   
  membership_audit_id                 Bigint         NOT NULL,
  discounts_id                        Bigint         NOT NULL,
  amount                              Decimal(18,3)  NOT NULL,
  last_modified_by                    Varchar(75)    NOT NULL,
  last_modified_date                  Timestamp      NOT NULL
)
;

CREATE TABLE membership_audit_status
(
  membership_audit_status_id  Bigint       NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  membership_id               Bigint       NOT NULL,
  membership_audit_id         Bigint       NOT NULL,
  version_number              Int          NOT NULL,
  event_type                  Varchar(30)  NOT NULL,
  event_datetime              Timestamp    NOT NULL,
  last_modified_by            Varchar(75)  NOT NULL,
  last_modified_date          Timestamp    NOT NULL
)
;

-- PRODUCT SUBJECT AREA

CREATE TABLE product_category
(
  product_category_id    Bigint       NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  product_category       Varchar(75)  NOT NULL,
  legacy_tid             Bigint       NULL,
  last_modified_by       Varchar(75)  NOT NULL,
  last_modified_date     Timestamp    NOT NULL,
  product_category_link  Varchar(128) NULL
  
)
;

CREATE TABLE product_category_association
(
  parent_product_category_id  Bigint       NOT NULL,
  child_product_category_id   Bigint       NOT NULL,
  last_modified_by            Varchar(75)  NOT NULL,
  last_modified_date          Timestamp    NOT NULL
)
;

CREATE TABLE product_category_translation
(
  product_category_translation_id  Bigint       NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  product_category_id              Bigint       NOT NULL,
  language_id                      Bigint       NOT NULL,
  translated_product_category      Varchar(75)  NOT NULL,
  last_modified_by                 Varchar(75)  NOT NULL,
  last_modified_date               Timestamp    NOT NULL
)
;

CREATE TABLE product_category_translation_level_one_display_order (
  product_category_translation_level_one_display_order_id     Bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  product_category_translation_id                             Bigint  NOT NULL,
  display_type                                                Varchar(75)  NOT NULL,
  display_order                                               Bigint  NOT NULL,
  is_visible_on_home_screen                                   Boolean      DEFAULT TRUE  NOT NULL,
  last_modified_by                                            Varchar(75)  NOT NULL,
  last_modified_date                                          Timestamp    NOT NULL
)
;

CREATE TABLE product
(
  product_id          Bigint       NOT NULL  GENERATED BY DEFAULT AS IDENTITY (START WITH 500000000),
  party_id            Bigint       NOT NULL,
  legacy_nid          Bigint       NULL,
  last_modified_by    Varchar(75)  NOT NULL,
  last_modified_date  Timestamp    NOT NULL,
)
;

CREATE TABLE hot_product_status
( 
  hot_product_id      Bigint       NOT NULL  GENERATED BY DEFAULT AS IDENTITY,   
  product_id          Bigint       NOT NULL,
  hot_product         Boolean      DEFAULT FALSE  NOT NULL,
  event_datetime      Timestamp    NOT NULL,
  last_modified_by    Varchar(75)  NOT NULL,
  last_modified_date  Timestamp    NOT NULL
)
;

CREATE TABLE hot_product_override
( 
  hot_product_override_id      Bigint       NOT NULL  GENERATED BY DEFAULT AS IDENTITY,  
  product_id                   Bigint       NOT NULL,
  last_modified_by             Varchar(75)  NOT NULL,
  last_modified_date           Timestamp    NOT NULL
)
;

CREATE TABLE product_membership
( 
  product_membership_id   Bigint       NOT NULL  GENERATED BY DEFAULT AS IDENTITY,   
  product_id              Bigint       NOT NULL,
  membership_id           Bigint       NOT NULL,
  event_datetime          Timestamp    NOT NULL,
  last_modified_by        Varchar(75)  NOT NULL,
  last_modified_date      Timestamp    NOT NULL
)
;

CREATE TABLE published_product_status
( 
  published_product_id  Bigint       NOT NULL  GENERATED BY DEFAULT AS IDENTITY,     
  product_id            Bigint       NOT NULL,
  is_published          Boolean      DEFAULT FALSE  NOT NULL,
  event_datetime        Timestamp    NOT NULL,
  last_modified_by      Varchar(75)  NOT NULL,
  last_modified_date    Timestamp    NOT NULL
)
;

CREATE TABLE product_audit
(
  product_audit_id        Bigint         NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  payment_term            Varchar(120),
  minimum_order           Varchar(20),
  freight_on_board_port   Varchar(75),
  freight_on_board_price  Varchar(100),
  country_of_origin       Varchar(75),
  lead_time               Varchar(20),
  model_number            Varchar(30),
  key_specification       Varchar(2000),
  meta_tag_list           Varchar(100),
  product_name            Varchar(60),
  product_description     Varchar(2000),
  keyword_list            Varchar(100),
  last_modified_by        Varchar(75)    NOT NULL,
  last_modified_date      Timestamp      NOT NULL
)
;

CREATE TABLE product_audit_translation
(
  product_audit_translation_id    Bigint         NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  product_audit_id                Bigint         NOT NULL,
  language_id                     Bigint         NOT NULL,
  translated_key_specification    Varchar(2000),
  translated_payment_term         Varchar(120),
  translated_product_name         Varchar(60),
  translated_product_description  Varchar(2000),
  translated_keyword_list         Varchar(100),
  translated_meta_tag_list        Varchar(100),
  last_modified_by                Varchar(75)    NOT NULL,
  last_modified_date              Timestamp      NOT NULL
)
;

CREATE TABLE product_category_product_audit
(
  product_category_id  Bigint       NOT NULL,
  product_audit_id     Bigint       NOT NULL,
  last_modified_by     Varchar(75)  NOT NULL,
  last_modified_date   Timestamp    NOT NULL
)
;

CREATE TABLE product_audit_image_link
(
  product_audit_image_link_id  Bigint  NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  product_audit_id       Bigint        NOT NULL,
  product_image_link     Varchar(100)  NOT NULL,
  is_primary             Boolean       DEFAULT FALSE  NOT NULL,
  last_modified_by       Varchar(75)   NOT NULL,
  last_modified_date     Timestamp     NOT NULL
)
;

CREATE TABLE product_audit_status
(
  product_audit_status_id  Bigint       NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  product_id               Bigint       NOT NULL,
  product_audit_id         Bigint       NOT NULL,
  version_number           Int          NOT NULL,
  event_type               Varchar(30)  NOT NULL,
  event_datetime           Timestamp    NOT NULL,
  last_modified_by         Varchar(75)  NOT NULL,
  last_modified_date       Timestamp    NOT NULL
)
;

-- CERTIFICATION SUBJECT AREA

CREATE TABLE certification
(
  certification_id    Bigint       NOT NULL  GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000000),
  last_modified_by    Varchar(75)  NOT NULL,
  last_modified_date  Timestamp    NOT NULL
)
;

CREATE TABLE product_certification
(
  certification_id    Bigint       NOT NULL,
  product_id          Bigint       NOT NULL,
  is_active           Boolean      DEFAULT FALSE  NOT NULL,
  last_modified_by    Varchar(75)  NOT NULL,
  last_modified_date  Timestamp    NOT NULL
)
;

CREATE TABLE party_certification
(
  certification_id           Bigint       NOT NULL,
  party_id                   Bigint       NOT NULL,
  is_active                  Boolean      DEFAULT FALSE  NOT NULL,
  last_modified_by           Varchar(75)  NOT NULL,
  last_modified_date         Timestamp    NOT NULL
)
;
CREATE TABLE certification_audit
(
  certification_audit_id  Bigint       NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  certification_standard  Varchar(30),
  certification_number    Varchar(30),
  certification_link      Varchar(100),
  issued_date             Date,
  scope_range			        Varchar(30),
  issued_by               Varchar(30),
  last_modified_by        Varchar(75)  NOT NULL,
  last_modified_date      Timestamp    NOT NULL
)
;

CREATE TABLE certification_audit_translation
(
  certification_audit_translation_id  Bigint        NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  certification_audit_id              Bigint        NOT NULL,
  language_id                         Bigint        NOT NULL,
  translated_certification_standard   Varchar(45),
  translated_certification_number     Varchar(75),
  translated_issued_by                Varchar(50),
  last_modified_by                    Varchar(75)   NOT NULL,
  last_modified_date                  Timestamp     NOT NULL
)
;

CREATE TABLE certification_audit_status
(
  certification_audit_status_id  Bigint       NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  certification_id               Bigint       NOT NULL,
  certification_audit_id         Bigint       NOT NULL,
  event_type                     Varchar(30)  NOT NULL,
  event_datetime                 Timestamp    NOT NULL,
  version_number                 Int          NOT NULL,
  last_modified_by               Varchar(75)  NOT NULL,
  last_modified_date             Timestamp    NOT NULL
)
;

-- MESSAGE SUBJECT AREA

CREATE TABLE message
(
  message_id          Bigint        NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  public_message_id   Varchar(20)   NULL,
  from_party_id       Bigint        NOT NULL,
  to_party_id         Bigint        NOT NULL,
  subject             Varchar(150)  NOT NULL,
  message_type        Varchar(20)   NOT NULL,
  last_modified_by    Varchar(75)   NOT NULL,
  last_modified_date  Timestamp     NOT NULL
);
CREATE UNIQUE INDEX public_message_id_AK ON message (public_message_id);

CREATE TABLE message_attachment
(
  message_attachment_id  Bigint        NOT NULL  GENERATED BY DEFAULT AS IDENTITY, 
  message_id              Bigint        NOT NULL,
  attachment_name         Varchar(100)  NOT NULL,
  attachment_link         Varchar(100)  NOT NULL,
  last_modified_by        Varchar(75)   NOT NULL,
  last_modified_date      Timestamp     NOT NULL
)
;

CREATE TABLE message_product
(
  message_id          Bigint       NOT NULL,
  product_id          Bigint       NOT NULL,
  last_modified_by    Varchar(75)  NOT NULL,
  last_modified_date  Timestamp    NOT NULL
)
;

CREATE TABLE message_buy_lead
(
  message_id             Bigint       NOT NULL,
  buy_lead_id            Bigint       NOT NULL,
  last_modified_by       Varchar(75)  NOT NULL,
  last_modified_date     Timestamp    NOT NULL
)
;

CREATE TABLE message_flag
(
  message_id          Bigint        NOT NULL,
  party_id            Bigint        NOT NULL,
  last_modified_by    Varchar(75)   NOT NULL,
  last_modified_date  Timestamp     NOT NULL
)
;

CREATE TABLE message_message_tag
(
  message_id          Bigint       NOT NULL,
  message_tag_id      Bigint       NOT NULL,
  last_modified_by    Varchar(75)  NOT NULL,
  last_modified_date  Timestamp    NOT NULL
)
;

CREATE TABLE interaction
(
  interaction_id      Bigint          NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  message_id          Bigint          NOT NULL,
  from_party_id       Bigint          NOT NULL,
  to_party_id         Bigint          NOT NULL,
  body                Varchar(4000)   NOT NULL,
  sent_timestamp      Timestamp       NOT NULL,
  read_by_receiver    Boolean         DEFAULT FALSE  NOT NULL,
  last_modified_by    Varchar(75)     NOT NULL,
  last_modified_date  Timestamp       NOT NULL
)
;

CREATE TABLE inquiry_basket
(
  party_id            Bigint       NOT NULL,
  product_id          Bigint       NOT NULL,
  last_modified_by    Varchar(75)  NOT NULL,
  last_modified_date  Timestamp    NOT NULL
)
;
CREATE UNIQUE INDEX inquiry_basket_AK ON inquiry_basket (party_id, product_id);

CREATE TABLE pending_inquiry
(
  pending_inquiry_id    Bigint         NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
  party_id              Bigint         NOT NULL,
  subject               Varchar(150)   NOT NULL,
  body                  Varchar(4000)  NOT NULL,
  submission_timestamp  Timestamp      NOT NULL,
  is_disapproved        Boolean        DEFAULT FALSE  NOT NULL,
  last_modified_by      Varchar(75)    NOT NULL,
  last_modified_date    Timestamp      NOT NULL
)
;

CREATE TABLE pending_inquiry_product
(
  pending_inquiry_id  Bigint       NOT NULL,
  product_id          Bigint       NOT NULL,
  last_modified_by    Varchar(75)  NOT NULL,
  last_modified_date  Timestamp    NOT NULL
)
;

CREATE TABLE pending_inquiry_message_tag
(
  pending_inquiry_id  Bigint       NOT NULL,
  message_tag_id      Bigint       NOT NULL,
  last_modified_by    Varchar(75)  NOT NULL,
  last_modified_date  Timestamp    NOT NULL
)
;

CREATE TABLE buy_lead
(
  buy_lead_id          Bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  party_id             Bigint       NOT NULL,
  product_category_id  Bigint       NOT NULL,
  effective_date       Date         NOT NULL,
  expiration_date      Date         NOT NULL,
  last_modified_by     Varchar(75)  NOT NULL,
  last_modified_date   Timestamp    NOT NULL
)
;

CREATE TABLE IF NOT EXISTS legacy_product_xref
(
  legacy_nid Int NOT NULL,
  product_id Int NOT NULL,
  last_modified_by Varchar(75) NOT NULL,
  last_modified_date Timestamp NOT NULL,
 PRIMARY KEY (legacy_nid)
)
;

