SELECT
  i.interaction_id,
  i.body,
  i.from_party_id as sender_party_id,
  slpv.public_party_id as sender_public_party_id,
  slpv.party_type as sender_party_type,
  slpv.user_id as sender_user_id,
  slpv.party_audit_id as sender_party_audit_id,
  slpv.ip_address as sender_ip_address,
  slpv.language_id as sender_language_id,
  slpv.year_established as sender_year_established,
  slpv.version_number as sender_version_number,
  slpv.event_type as sender_event_type,
  slpv.last_modified_by as sender_last_modified_by,
  slpv.event_datetime as sender_event_datetime,
  slpv.license_link as sender_license_link,
  slpv.company_logo_link as sender_company_logo_link,
  slpv.company_name_english as sender_company_name_english,
  slpv.company_name_chinese as sender_company_name_chinese,
  slpv.company_description as sender_company_description,
  slpv.number_of_employees as sender_number_of_employees,
  slpv.company_website as sender_company_website,
  slpv.total_annual_sales as sender_total_annual_sales,
  slpv.total_imports_us_dollars as sender_total_imports_us_dollars,
  slpv.first_name as sender_first_name,
  slpv.last_name as sender_last_name,
  slpv.mobile_phone as sender_mobile_phone,
  slpv.business_phone as sender_business_phone,
  slpv.skype_id as sender_skype_id,
  slpv.msn_id as sender_msn_id,
  slpv.icq_id as sender_icq_id,
  slpv.email_address as sender_email_address,
  slpv.province as sender_province,
  slpv.gender as sender_gender,
  slpv.title as sender_title,
  slpv.country as sender_country,
  slpv.registration_date as sender_registration_date,
  i.to_party_id as receiver_party_id,
  rlpv.public_party_id as receiver_public_party_id,
  rlpv.party_type as receiver_party_type,
  rlpv.user_id as receiver_user_id,
  rlpv.party_audit_id as receiver_party_audit_id,
  rlpv.ip_address as receiver_ip_address,
  rlpv.language_id as receiver_language_id,
  rlpv.year_established as receiver_year_established,
  rlpv.version_number as receiver_version_number,
  rlpv.event_type as receiver_event_type,
  rlpv.last_modified_by as receiver_last_modified_by,
  rlpv.event_datetime as receiver_event_datetime,
  rlpv.license_link as receiver_license_link,
  rlpv.company_logo_link as receiver_company_logo_link,
  rlpv.company_name_english as receiver_company_name_english,
  rlpv.company_name_chinese as receiver_company_name_chinese,
  rlpv.company_description as receiver_company_description,
  rlpv.number_of_employees as receiver_number_of_employees,
  rlpv.company_website as receiver_company_website,
  rlpv.total_annual_sales as receiver_total_annual_sales,
  rlpv.total_imports_us_dollars as receiver_total_imports_us_dollars,
  rlpv.first_name as receiver_first_name,
  rlpv.last_name as receiver_last_name,
  rlpv.mobile_phone as receiver_mobile_phone,
  rlpv.business_phone as receiver_business_phone,
  rlpv.skype_id as receiver_skype_id,
  rlpv.msn_id as receiver_msn_id,
  rlpv.icq_id as receiver_icq_id,
  rlpv.email_address as receiver_email_address,
  rlpv.province as receiver_province,
  rlpv.gender as receiver_gender,
  rlpv.title as receiver_title,
  rlpv.country as receiver_country,
  rlpv.registration_date as receiver_registration_date,
  i.sent_timestamp,
  i.read_by_receiver
FROM interaction i
  INNER JOIN latest_party_view slpv ON i.from_party_id = slpv.party_id
  INNER JOIN latest_party_view rlpv ON i.to_party_id = rlpv.party_id
